unqualified-search-registries = ["docker.io"]

[[registry]]
prefix = "docker.io"
insecure = true
location = "docker.lan:5050/docker.io"

[[registry]]
prefix = "ghcr.io"
insecure = true
location = "docker.lan:5050/ghcr.io"

[[registry]]
prefix = "quay.io"
insecure = true
location = "docker.lan:5050/quay.io"


#https://github.com/containers/image/blob/main/docs/containers-registries.conf.5.md
