set runtimepath=~/.vim/,$VIMRUNTIME,~/.vim/bundle/vim-snippets/,~/.vim/after/

" Normally we use vim-extensions. If you want true vi-compatibility
" remove change the following statements
set nocompatible    " Use Vim defaults instead of 100% vi compatibility
set backspace=indent,eol,start  " more powerful backspacing

" Now we set some defaults for the editor
" set autoindent    " always set autoindenting on
" set linebreak     " Don't wrap words by default
set textwidth=0     " Don't wrap lines by default
set nobackup
" place for swap files
set dir=~/fshare/.tmp
set viminfo='20,\"50    " read/write a .viminfo file, don't store more than
                        " 50 lines of registers
set viminfo+=n~/fshare/.tmp/.viminfo
"http://stackoverflow.com/questions/6286866/how-to-tell-vim-to-store-the-viminfo-file-somewhere-else
"http://vim.1045645.n5.nabble.com/search-vimrc-and-viminfo-in-a-different-directory-td4391875.html
set history=50  " keep 50 lines of command line history
set ruler       " show the cursor position all the time

" modelines have historically been a source of security/resource
" vulnerabilities -- disable by default, even when 'nocompatible' is set
set nomodeline

" Suffixes that get lower priority when doing tab completion for filenames.
" These are files we are not likely to want to edit or read.
set suffixes=.bak,~,.swp,.o,.info,.aux,.log,.dvi,.bbl,.blg,.brf,.cb,.ind,.idx,.ilg,.inx,.out,.toc


" Vim5 and later versions support syntax highlighting. Uncommenting the next
" line enables syntax highlighting by default.
" enable by Plug
" syntax on

" If using a dark background within the editing area and syntax highlighting
" turn on this option as well
"set background=dark

" The following are commented out as they cause vim to behave a lot
" differently from regular Vi. They are highly recommended though.
set showcmd     " Show (partial) command in status line.
set showmatch       " Show matching brackets.
"set ignorecase     " Do case insensitive matching
"set smartcase      " Do smart case matching
set incsearch       " Incremental search
set autowrite       " Automatically save before commands like :next and :make
set hidden              " Hide buffers when they are abandoned
set wic         " Wildignorecase for cmdline completion especially for filename
"set mouse=a        " Enable mouse usage (all modes) in terminals
set fencs=utf-8,ucs-bom,cp936,gb18310,big5,latin1
set title

"https://groups.google.com/forum/#!msg/vim_use/SR12FCxkQYg/aZIGO33waN0J
set diffexpr=MyDiff()
function MyDiff()
  let opt = ""
  if &diffopt =~ "icase"
    let opt = opt . "-i "
  endif
  if &diffopt =~ "iwhite"
    let opt = opt . "-b "
  endif
  silent execute "!diff -a --binary " . opt . v:fname_in . " " . v:fname_new .
    \  " > " . v:fname_out
endfunction

runtime! ftplugin/man.vim

if !empty($TMUX)"http://stackoverflow.com/questions/9496769/how-to-correctly-use-undefined-environment-variables-in-vimrc
  if &term =~ "screen"
    set t_ts=k "<C-v><C-]>
    set t_fs=\
  endif
endif

if has("autocmd")
  " Uncomment the following to have Vim jump to the last position when
  " reopening a file
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$") | exe "normal g'\"" | endif

  "http://superuser.com/questions/251019/customizing-tmux-status-to-represent-current-working-directory-and-files
  "http://stackoverflow.com/questions/15123477/tmux-tabs-with-name-of-file-open-in-vim
  "http://vim.wikia.com/wiki/Automatically_set_screen_title
  if !empty($TMUX)
    autocmd BufEnter * let &titlestring = expand('%:.') . ' - VIM'  "TODO man
    auto VimLeave * :set t_ts=k\
    "autocmd BufReadPost,FileReadPost,BufNewFile * call system("tmux rename-window ". expand("%:t"))
  endif
endif " has ("autocmd")

" cd to the directory containing the file in the buffer
" https://github.com/olalonde/dotfiles/blob/master/tag-vim/vimrc#L189
nmap <silent> <leader>cd :lcd %:h<CR>
noremap <F12> :e ~/.vim/vimrc<CR>
inoremap <F12> <ESC>:e ~/.vim/vimrc<CR>
"nnoremap <C-H> <C-W>h
"nnoremap <C-J> <C-W>j
"nnoremap <C-K> <C-W>k
"nnoremap <C-L> <C-W>l
"imap <C-Tab> <ESC><C-6>i
" Swap the word the cursor is on with the next word (which can be on a
" newline, and punctuation is "skipped"):
" http://superuser.com/questions/290360/how-to-switch-words-in-an-easy-manner-in-vim
nmap <silent> gw "_yiw:s/\(\%#\w\+\)\(\_W\+\)\(\w\+\)/\3\2\1/<CR><C-o>:noh<CR>

if has('gui_running')
  " Make shift-insert work like in Xterm
  map <S-Insert> <MiddleMouse>
  map! <S-Insert> <MiddleMouse>
endif

set pastetoggle=<F9>  "http://stackoverflow.com/questions/2514445/turning-off-auto-indent-when-pasting-text-into-vim

" Allows writing to files with root priviledges
cmap w!! w !sudo tee % > /dev/null

" https://www.reddit.com/r/vim/comments/4l00pj/eli5_why_is_nerdtree_discouraged_but_everyone/d3jufab
" I don't use these methods of installing vim plugins.
let g:loaded_getscriptPlugin = 0
let g:loaded_vimballPlugin = 0
let g:loaded_netrwPlugin = 0
" LogiPat seems useful, but I've never touched it.
let g:loaded_logiPat = 0

let g:on_demand_autoformat_fts = [ '\<cpp\>', '\<c\>', '\<javascript*', '\<go\>', 'python', 'rust' ]
let g:on_demand_fts = g:on_demand_autoformat_fts + [ 'vim', 'ruby' ]
let g:on_demand_ft_regex = join(g:on_demand_fts, '\|')

"Vim-Plug
"https://github.com/junegunn/vim-plug
let g:plug_timeout=600000 "ycm https://github.com/junegunn/vim-plug/issues/75
call plug#begin('~/.vim/bundle/')

"bundles

"Plug 'mattn/emmet-vim', { 'for': ['html', 'css']}
"let g:user_emmet_install_global = 0
Plug 'Raimondi/delimitMate', { 'for': g:on_demand_fts }
Plug 'SirVer/ultisnips', { 'for': [] } | Plug 'git@github.com:kayw/vim-snippets.git'
"Plug 'scrooloose/syntastic'
Plug 'tpope/vim-fugitive' "http://vimcasts.org/episodes/fugitive-vim-working-with-the-git-index/
Plug 'vim-scripts/python_match.vim'
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }

Plug 'Valloric/YouCompleteMe', { 'do': './install.py --clang-completer --system-libclang --tern-completer', 'on': [] }
Plug 'pangloss/vim-javascript', { 'for': 'javascript*' }
Plug 'mxw/vim-jsx', { 'for': 'javascript.jsx' }
Plug 'wting/rust.vim', {'for': 'rust'}
Plug 'fatih/go.vim', {'for': 'go'}
Plug 'cakebaker/scss-syntax.vim', {'for': 'scss'}

Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'altercation/vim-colors-solarized'

Plug 'junegunn/fzf', { 'do': './install --all' } "https://www.reddit.com/r/vim/comments/4l00pj/eli5_why_is_nerdtree_discouraged_but_everyone/d3juidx
Plug 'junegunn/fzf.vim'
Plug 'ap/vim-buftabline' "https://www.reddit.com/r/vim/comments/4l00pj/eli5_why_is_nerdtree_discouraged_but_everyone/d3nyg6n

Plug 'scrooloose/nerdcommenter', { 'for': g:on_demand_fts }
Plug 'octol/vim-cpp-enhanced-highlight', { 'for': 'cpp' } "differ highlight for macro namespace type
Plug 'Chiel92/vim-autoformat', { 'for': g:on_demand_autoformat_fts }
Plug 'w0rp/ale'
call plug#end()

" Enabled file type detection
" Use the default filetype settings. If you also want to load indent files
" to automatically do language-dependent indenting add 'indent' as well.
filetype plugin on
" Uncomment the following to have Vim load indentation rules according to the
" detected filetype.
filetype indent on

"UltiSnip
"ycm TAB key TODO https://github.com/Valloric/YouCompleteMe/issues/36
let g:UltiSnipsExpandTrigger = "<C-e>"
let g:UltiSnipsListSnippets = "<C-g>"
let g:UltiSnipsJumpForwardTrigger="<C-e>"
let g:UltiSnipsJumpBackwardTrigger="<c-f>"
" this mapping Enter key to <C-y> to chose the current highlight item
" " and close the selection list, same as other IDEs.
" " CONFLICT with some plugins like tpope/Endwise
inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
let g:snips_author="kayw"

"let g:UltiSnipsSnippetDirectories=["UltiSnips", "snippets"]

"airline
set laststatus=2 "http://superuser.com/questions/634570/vim-how-to-install-airline
let g:airline_theme='badwolf'
let g:airline#extensions#disable_rtp_load = 1
let g:airline_powerline_fonts = 1

" Nerd tree
nmap <Leader>t :let NERDTreeQuitOnOpen = 1<bar>NERDTreeToggle<CR>

"YouCompleteMe
let g:ycm_autoclose_preview_window_after_completion = 1
let g:ycm_global_ycm_extra_conf = '~/.vim/compiler/global.ycm_extra_conf.py'
let g:ycm_confirm_extra_conf = 0
let g:ycm_complete_in_comments = 1
noremap <Leader>k :YcmCompleter GoToDefinitionElseDeclaration<CR>
inoremap <Leader>k :YcmCompleter GoToDefinitionElseDeclaration<CR>
"https://github.com/junegunn/vim-plug/issues/444#issuecomment-195363891  au FileType javascript.jsx change twice autocommand nested e218 save e13 ycm load twice => use if &ft
"https://github.com/junegunn/vim-plug/wiki/faq#loading-plugins-manually
"https://github.com/Valloric/YouCompleteMe/issues/893#issuecomment-53151235
augroup ycmonload
  au!
  au BufReadPost,BufEnter * if &ft =~? g:on_demand_ft_regex |
                 \ let g:autoformat_autoindent = 0 |
                 \   set nu |
                 \ endif
  au! InsertEnter *  call plug#load('ultisnips')
  au InsertEnter * if &ft =~? g:on_demand_ft_regex |
                   \ call plug#load('YouCompleteMe') |
                   \ let g:autoformat_autoindent = 0 |
                   \ endif |
                   \ au! ycmonload
augroup END

"ALE
let g:ale_lint_on_text_changed = 'never'
let g:ale_open_list = 1

let g:ale_fixers = {
      \   'javascript': ['eslint'],
      \}
let g:ale_fix_on_save = 1

"fzf
"copy from leaderf
nnoremap <leader>f :<C-U>Files<CR>
nnoremap <leader>b :<C-U>Buffers<CR>

" https://github.com/junegunn/fzf.vim/issues/92
" AgM: case sensitive Ag call
autocmd VimEnter * command! -nargs=* -bang AgM call fzf#vim#ag_raw('-s '.fzf#shellescape('\b'.expand('<cword>').'\b'))

nnoremap ;s :AgM<CR>
" \b\s?<C-R><C-W>\b<CR>   "http://vi.stackexchange.com/a/3168
" <C-R><C-W> word begin with b will eat \b
"nnoremap ;s :<C-u>execute 'Ag! \b'.expand('<cword>').'\b'<CR>
" result window "cover the whole because of -bang ! <bang>0
vnoremap ;s :<C-U>
            \let old_reg=getreg('"')<Bar>let old_regtype=getregtype('"')<CR>
            \gvy:Ag <C-R><C-R>=substitute(
            \escape(@", '/\.*$^~['), '\_s\+', '\\_s\\+', 'g')<CR><CR>
            \gV:call setreg('"', old_reg, old_regtype)<CR>
"https://www.reddit.com/r/vim/comments/4ffvt1/is_there_a_way_to_switch_between_fzf_commands/

"http://vim.wikia.com/wiki/Search_for_visually_selected_text
vnoremap <silent> * :<C-U>
                    \let old_reg=getreg('"')<Bar>let old_regtype=getregtype('"')<CR>
                    \gvy/<C-R><C-R>=substitute(
                    \escape(@", '/\.*$^~['), '\_s\+', '\\_s\\+', 'g')<CR><CR>
                    \gV:call setreg('"', old_reg, old_regtype)<CR>

vnoremap <silent> # :<C-U>
                    \let old_reg=getreg('"')<Bar>let old_regtype=getregtype('"')<CR>
                    \gvy?<C-R><C-R>=substitute(
                    \escape(@", '?\.*$^~['), '\_s\+', '\\_s\\+', 'g')<CR><CR>
                    \gV:call setreg('"', old_reg, old_regtype)<CR>

"https://github.com/junegunn/fzf.vim/issues/27
function! s:ag_in(...)
  call fzf#vim#ag(join(a:000[1:], ' '), {'dir': a:1})
endfunction
"AgIn dir pattern
command! -nargs=+ -complete=dir AgIn call s:ag_in(<f-args>)

"delimitMate
au FileType vim let b:delimitMate_matchpairs = "(:),[:],{:},<:>"
             \| let b:delimitMate_quotes = "' `"

"javascript-vim
let javascript_enable_domhtmlcss=1
let g:jsx_ext_required = 0

"autoformat
"http://stackoverflow.com/a/23496781
"autocmd BufWritePre *.{js,jsx,go,py,go,rs} :Autoformat
"http://stackoverflow.com/a/27334950
"au BufWritePre * if &ft =~? join(g:on_demand_autoformat_fts, '\|') | Autoformat | endif

let g:formatters_python = [ 'yapf' ]
let g:formatter_yapf_style = 'chromium'

"buftabline
let g:buftabline_numbers = 1
let g:buftabline_indicators = 1

"colorscheme
set background=light "dark
let g:solarized_contrast="low"
let g:solarized_visibility="high"
if $TERM =~ "-256color"
  se t_Co=256
  let g:solarized_termcolors=256
  let g:solarized_contrast="high"
  let g:solarized_termtrans=1
endif
colo solarized
